remote_theme: benbalter/retlab
name: MeDuSA

project:
  version: 1.0.0
  download_url: https://github.com/LeonSong1995/MeDuSA
  download_text: Download

# Build settings
markdown: kramdown
exclude:
  - LICENSE.md
  - README.md
